export const ADD_BOOK_IN_BASKET = 'BOOK_SHOP/APP_REDUCER/ADD_BOOK_IN_BASKET';
export const DELETE_BOOK_IN_BASKET = 'BOOK_SHOP/APP_REDUCER/DELETE_BOOK_IN_BASKET';
export const SET_PAGE_COUNT = 'BOOK_SHOP/APP_REDUCER/SET_PAGE_COUNT';
export const CHANGE_CURRENT_PAGE = 'BOOK_SHOP/APP_REDUCER/CHANGE_CURRENT_PAGE';
export const SET_TOTAL_USERS_COUNT = 'BOOK_SHOP/APP_REDUCER/SET_TOTAL_USERS_COUNT';
export const SET_CURRENT_PAGE = 'BOOK_SHOP/APP_REDUCER/SET_CURRENT_PAGE';
