export const SET_FILTER_VALUE = 'BOOK_SHOP/APP_REDUCER/SET_FILTER_VALUE';
export const SET_SEARCH_LIST = 'BOOK_SHOP/APP_REDUCER/SET_SEARCH_LIST';
export const ADD_BOOK_IN_BASKET_LIST = 'BOOK_SHOP/APP_REDUCER/ADD_BOOK_IN_BASKET_LIST';
export const CLEAN_BASKET_LIST = 'BOOK_SHOP/APP_REDUCER/CLEAN_BASKET_LIST';
export const DELETE_BOOK_FROM_BASKET_LIST =
  'BOOK_SHOP/APP_REDUCER/DELETE_BOOK_FROM_BASKET_LIST';
export const INCREMENT_BOOK_QUANTITY_IN_BASKET_LIST =
  'BOOK_SHOP/APP_REDUCER/INCREMENT_BOOK_QUANTITY_IN_BASKET_LIST';
export const DECREMENT_BOOK_QUANTITY_IN_BASKET_LIST =
  'BOOK_SHOP/APP_REDUCER/DECREMENT_BOOK_QUANTITY_IN_BASKET_LIST';
export const SET_HISTORY_FROM_SESSION_STORAGE =
  'BOOK_SHOP/APP_REDUCER/SET_HISTORY_FROM_SESSION_STORAGE';
